# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: '#about'
    weight: 10
  - name: 知乎
    url: '#posts'
    weight: 20
  - name: 指南
    url: '#projects'
    weight: 40
  - name: 视频
    url: '#talks'
    weight: 50
  - name: 文献
    url: '#publications'
    weight: 60
  - name: 联系
    url: '#contact'
    weight: 80
  - name: 笔记
    url: 'course'
    weight: 70
  - name: Notion
    url: '#featured'
    weight: 30
  - name: Researcher
    url: 'https://www.researcher-app.com/feed/all'
    weight: 90
  - name: Cabibre-web
    url: 'http://106.113.188.127:64544/'
    weight: 100  
  name: RSS
    url: 'https://feedly.com/i/discover'
    weight: 110  

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
