---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/admin
  label: Admin
  create: all
  match: "**/*"
- type: directory
  path: content/authors
  label: Authors
  create: all
  match: "**/*"
- type: directory
  path: content/course
  label: Course
  create: all
  match: "**/*"
- type: directory
  path: content/event
  label: Event
  create: all
  match: "**/*"
- type: directory
  path: content/home
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
- type: directory
  path: content/project
  label: Project
  create: all
  match: "**/*"
- type: directory
  path: content/publication
  label: Publication
  create: all
  match: "**/*"
- type: directory
  path: content/slides
  label: Slides
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: https://cloudinary.com/console/c-918e4f77ee01fce052bbfcb23436e4/media_library/folders/79afee93ebd520abb854255305ba2bae
public_path: " https://res.cloudinary.com/aliyisheng/image/upload/c_scale,w_auto:100,dpr_auto"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
